# print("result:", 5 // 3)
# print("result:", max(5,6,3,0,2, -3,5))
# print("result:", min(5,6,3,0,2, -3,5))
# print("result:", abs(-5))
# print("result:", pow(5, 3))   
# print("result:", round(5 / 3))
# print('Second \' \t \\ l\ni\nn\e')
# print("result:", 7, 15, sep="", end="!\n")

input("Enter your age ")
