name: Build Python Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build binaries from basics folder
      run: |
        cd basics
        for file in *.py; do
          echo "Building $file..."
          pyinstaller --onefile --distpath ../dist "$file"
        done
        cd ..
        ls -la dist/

    - name: Upload all binaries
      uses: actions/upload-artifact@v4
      with:
        name: python-binaries
        path: dist/*
